/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_samsung_ds_tracemon_worker_util_Decoder */

#ifndef _Included_com_samsung_ds_tracemon_worker_util_Decoder
#define _Included_com_samsung_ds_tracemon_worker_util_Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_samsung_ds_tracemon_worker_util_Decoder
 * Method:    decode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_samsung_ds_tracemon_worker_util_Decoder_decode
        (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
